name: Build and Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Generate documentation
      run: |
        sudo apt-get install -y doxygen
        doxygen Doxyfile
      working-directory: D:\a\TRPP_Labs\TRPP_Labs

    - name: Archive documentation
      uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: D:\a\TRPP_Labs\TRPP_Labs\doc
