name: Build and Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release
      
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))


    - name: Install Doxygen
      run: choco install doxygen.install -y

    - name: Generate documentation
      run: doxygen Doxyfile
      working-directory: D:\a\TRPP_Labs\TRPP_Labs

    - name: Archive documentation
      uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: D:\a\TRPP_Labs\TRPP_Labs\doc
